/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.componentes.ui.panels;

import com.componentes.controllers.PersistenceManager;
import com.componentes.entitys.Asignaciones;
import com.componentes.entitys.Empleados;
import com.componentes.entitys.Proyectos;
import com.componentes.entitys.Vacaciones;
import com.componentes.services.AsignacionService;
import com.componentes.services.EmpleadoService;
import com.componentes.services.ProyectoService;
import com.componentes.services.VacacionService;
import com.componentes.utils.TablaUtils;
import jakarta.persistence.EntityManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author chris
 */
public class AsignacionPanel extends javax.swing.JPanel {

    EntityManager em;

    Proyectos proyecto;
    Empleados empleado;
    Asignaciones asignaciones;

    ProyectoService proyectoService;
    EmpleadoService empleadoService;
    AsignacionService asignacionService;

    /**
     * Creates new form AsignacionPanel
     */
    public AsignacionPanel() {
        initComponents();

        em = PersistenceManager.getEntityManager();

        // Obtén la fecha actual
        Date fechaActual = new Date();

        // Crea un formato de fecha
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/dd");

        // Convierte la fecha actual a un String en el formato deseado
        String fechaActualTexto = formatoFecha.format(fechaActual);

        // Establece el texto en el JTextField
        TxtFechaInicioA1.setText(fechaActualTexto);
        rellenarTabla();

        jTable4.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Verificar si la selección de fila cambió
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = jTable4.getSelectedRow();
                    if (selectedRow != -1) {
                        // Obtener datos de la fila seleccionada y hacer lo que necesites
                        Object id = jTable4.getValueAt(selectedRow, 0);
                        Object Fecha_inicio = jTable4.getValueAt(selectedRow, 1);
                        Object Fecha_fin = jTable4.getValueAt(selectedRow, 2);
                        Object proyecto = jTable4.getValueAt(selectedRow, 3);
                        Object empleado = jTable4.getValueAt(selectedRow, 4);
                        Object tarea = jTable4.getValueAt(selectedRow, 5);

                        TxtFechaInicioA1.setText(Fecha_inicio.toString());
                        TxtFechaFinA.setText(Fecha_fin.toString());
                        TxtIdProyecto.setText(proyecto.toString());
                        TxtIdEmpleado1.setText(empleado.toString());
                        tareaTxt.setText(tarea.toString());

                        asignaciones.setId(Integer.parseInt(id.toString()));
                    }
                }
            }
        });

    }

    public void rellenarTabla() {
        try (EntityManager em = PersistenceManager.getEntityManager()) {
            // Para asignaciones
            AsignacionService asignacionService = new AsignacionService();

            String[] columnsAsignaciones = {"id", "Fecha de inicio", "Fecha de fin", "id proyecto", "id empleado", "Tarea asignada"};
            List<Asignaciones> asignaciones = asignacionService.readAll(em);
            String[] attAsignaciones = {"Id", "FechaInicio", "FechaFin", "Proyecto.Id", "Empleado.Id", "Tarea"};
            TablaUtils.rellenarTabla(jTable4, columnsAsignaciones, asignaciones, attAsignaciones);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "asignacion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            PersistenceManager.closeEntityManager(em);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TxtFechaFinA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtFechaInicioA1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtIdProyecto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tareaTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtIdEmpleado1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        BtnGuardarAsignacion = new javax.swing.JButton();
        BtnLimpiarAsignacion = new javax.swing.JButton();
        BtnCancelarAsignacion = new javax.swing.JButton();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha de inicio");

        TxtFechaFinA.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Fecha de fin");

        TxtFechaInicioA1.setBackground(new java.awt.Color(204, 204, 204));
        TxtFechaInicioA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechaInicioA1ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Id del proyecto");

        TxtIdProyecto.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Id del empleado");

        tareaTxt.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Tarea asignada");

        TxtIdEmpleado1.setBackground(new java.awt.Color(204, 204, 204));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha de inicio", "Fecha de fin", "Id proyecto", "Id empleando", "Tarea asignada"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        BtnGuardarAsignacion.setBackground(new java.awt.Color(0, 0, 153));
        BtnGuardarAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarAsignacion.setText("Guardar");
        BtnGuardarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarAsignacionActionPerformed(evt);
            }
        });

        BtnLimpiarAsignacion.setBackground(new java.awt.Color(102, 102, 255));
        BtnLimpiarAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarAsignacion.setText("Limpiar");
        BtnLimpiarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarAsignacionActionPerformed(evt);
            }
        });

        BtnCancelarAsignacion.setBackground(new java.awt.Color(255, 0, 0));
        BtnCancelarAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelarAsignacion.setText("Eliminar");
        BtnCancelarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtFechaFinA)
                            .addComponent(TxtIdProyecto)
                            .addComponent(tareaTxt)
                            .addComponent(TxtIdEmpleado1)
                            .addComponent(TxtFechaInicioA1)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnLimpiarAsignacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(BtnGuardarAsignacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCancelarAsignacion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFechaInicioA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFechaFinA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtIdEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tareaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardarAsignacion)
                            .addComponent(BtnCancelarAsignacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpiarAsignacion)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarAsignacionActionPerformed
        try (EntityManager em = PersistenceManager.getEntityManager()) {
            if (!TxtFechaFinA.getText().equals("")
                    && !tareaTxt.getText().equals("") && !TxtIdEmpleado1.getText().equals("")
                    && !TxtIdProyecto.getText().equals("")) {

                asignaciones = new Asignaciones();

                asignacionService = new AsignacionService();
                ProyectoService proyectoService = new ProyectoService();
                EmpleadoService empleadoService = new EmpleadoService();

                // Capturar fechas
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/dd");
                java.util.Date fechaInicio = formatoFecha.parse(TxtFechaInicioA1.getText());
                java.util.Date fechaFinal = formatoFecha.parse(TxtFechaFinA.getText());

                // Convertir fechas a objetos java.sql.Date
                java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
                java.sql.Date sqlFechaFinal = new java.sql.Date(fechaFinal.getTime());

                asignaciones.setFechaInicio(sqlFechaInicio);
                asignaciones.setFechaFin(sqlFechaFinal);

                // Capturar ID del empleado
                int idEmpleado = Integer.parseInt(TxtIdEmpleado1.getText());
                empleado = empleadoService.read(em, idEmpleado); // Modificado para obtener el empleado correctamente
                asignaciones.setEmpleado(empleado);

                // Capturar ID del proyecto
                int idProyecto = Integer.parseInt(TxtIdProyecto.getText());
                proyecto = proyectoService.read(em, idProyecto); // Modificado para obtener el proyecto correctamente
                asignaciones.setProyecto(proyecto);

                // Capturar tarea y guardar en la base de datos
                asignaciones.setTarea(tareaTxt.getText());

                asignacionService.create(em, asignaciones);

                JOptionPane.showMessageDialog(null, "Tarea asignada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Rellene los campos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            PersistenceManager.closeEntityManager(em);
            rellenarTabla();
        }
    }//GEN-LAST:event_BtnGuardarAsignacionActionPerformed

    private void BtnLimpiarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarAsignacionActionPerformed
        TxtFechaInicioA1.setText("");
        TxtFechaFinA.setText("");
        TxtIdProyecto.setText("");
        TxtIdEmpleado1.setText("");
        tareaTxt.setText("");
    }//GEN-LAST:event_BtnLimpiarAsignacionActionPerformed

    private void BtnCancelarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarAsignacionActionPerformed
        try (EntityManager em = PersistenceManager.getEntityManager()) {

            asignacionService = new AsignacionService();

            if (asignaciones.getId() != null) {
                asignacionService.delete(em, asignaciones.getId());
                JOptionPane.showMessageDialog(null, "Eliminado correctamente", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un elemento", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            PersistenceManager.closeEntityManager(em);
            rellenarTabla();
        }
    }//GEN-LAST:event_BtnCancelarAsignacionActionPerformed

    private void TxtFechaInicioA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechaInicioA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechaInicioA1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelarAsignacion;
    private javax.swing.JButton BtnGuardarAsignacion;
    private javax.swing.JButton BtnLimpiarAsignacion;
    private javax.swing.JTextField TxtFechaFinA;
    private javax.swing.JTextField TxtFechaInicioA1;
    private javax.swing.JTextField TxtIdEmpleado1;
    private javax.swing.JTextField TxtIdProyecto;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField tareaTxt;
    // End of variables declaration//GEN-END:variables
}
